import type { Metadata } from "next";
import "./styles/reset.scss"
import "./styles/theme.scss"
import {roboto} from './fonts/fonts'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        {children}
      </body>
    </html>
  );
}
